# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: SprintBoot app

on:
  #  push:
  #    branches: [ "develop" ]
  pull_request:
    branches: 
      - develop
      - feature_*
    types:
      - opened
      - edited
      - synchronize
      - closed

jobs:
  pullrequest-feature:
    if: contains('${{github.ref_name}}', 'feature')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.head_ref }}"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Cacheado de Maven para acelerar el despliegue
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: file-checks
        uses: ./.github/test/checks/
      - name: junit-tests
        uses: ./.github/test/junit/
#      - name: sonarqube
 #       uses: ./.github/test/sonarqube/
 #       env:
 #         SONAR_TOKEN: ${{ vars.SONAR_TOKEN }}
 #         SONAR_URL: ${{ vars.SONAR_URL }}
  automerge:
    needs: 'pullrequest-feature'
    if: contains('${{github.ref_name}}', 'feature')
    runs-on: ubuntu-latest

    steps:
      - name: execute merge
        uses: "gsoc2/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN_PULLREQ }}"
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_METHOD: "rebase"
          PULL_REQUEST: "${{ github.event.pull_request.number }}"
          LOG: "DEBUG"
  pullrequest-develop:
    needs: 'automerge'
    if: contains('${{github.ref_name}}', 'develop')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.head_ref }}"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Cacheado de Maven para acelerar el despliegue
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: file-checks
        uses: ./.github/test/checks/
      - name: junit-tests
        uses: ./.github/test/junit/
#      - name: sonarqube
#        uses: ./.github/test/sonarqube/
#        env:
#          SONAR_TOKEN: ${{ vars.SONAR_TOKEN }}
#          SONAR_URL: ${{ vars.SONAR_URL }}
#      - name: docker-image
#        uses: ./.github/test/docker/
 